import Head from "next/head";
import Image from "next/image";
import Section from "../components/section";
import SectionHeading from "../components/sectionHeading";
import ProgramItem from "../components/programItem";
import Button from "../components/button";
import { programItems } from "../constants/programItems";
import SectionHeader from "../components/sectionHeader";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <h3 className="text-xl font-bold">WORK HARDER, GET STRONGER</h3>
        <h2 className="text-7xl font-black pt-7 pb-9">EASY WITH OUT GYM</h2>
        <Button text="BECOME A MEMBER" />
      </Section>
      <Section>
        <SectionHeader
          heading={
            <>
              Choose <span className="text-orange-700">Program</span>
            </>
          }
          subHeading="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          rem nostrum, deserun dolor delectus."
        />
        <div className="flex flex-row flex-wrap">
          {programItems.map((item, index) => {
            return (
              <ProgramItem
                key={index}
                title={item.title}
                description={item.description}
                link={item.link}
              />
            );
          })}
        </div>
      </Section>
      <Section>
        <SectionHeader
          heading={
            <>
              Don&apos;t <span className="text-orange-700">Think</span>, Begin{" "}
              <span className="text-orange-700">Today</span>
            </>
          }
          subHeading="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed,
          provident dolores? Iste illo, aperiam sit dolore quis, nobis
          laudantium. Lorem ipsum dolor sit amet."
        />
        <Button text="Become a member" />
      </Section>
      <Section>
      <SectionHeader
          heading={
            <>
              Our <span className="text-orange-700">Classes</span>
            </>
          }
          subHeading="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed,
          provident dolores? Iste illo, aperiam sit dolore quis, nobis
          laudantium. Lorem ipsum dolor sit amet."
        />
      </Section>
    </>
  );
};

export default HomePage;
