import Head from "next/head";
import Image from "next/image";
import Section from "../components/section";
import SectionHeading from "../components/sectionHeading";
import ProgramItem from "../components/programItem";
import { programItems } from "../constants/programItems";

const BorderImg = () => (
  <Image
    className="mx-auto"
    src="https://altcampus.github.io/training-studio/assets/media/line-dec.png"
    alt="border"
    width={45}
    height={15}
  />
);

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <h3 className="text-xl font-bold">WORK HARDER, GET STRONGER</h3>
        <h2 className="text-7xl font-black pt-7 pb-9">EASY WITH OUT GYM</h2>
        <button className="w-fit bg-white mx-auto px-5 py-4 font-medium">
          BECOME A MEMBER
        </button>
      </Section>
      <Section>
        <SectionHeading className="mb-4">
          Choose <span className="text-orange-700">Program</span>
        </SectionHeading>
        <BorderImg />
        <p className="my-4 font-extralight max-w-md mx-auto">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          rem nostrum, deserun dolor delectus.
        </p>
        <div className="flex flex-row flex-wrap">
          {programItems.map((item, index) => {
            return (
              <ProgramItem
                key={index}
                title={item.title}
                description={item.description}
                link={item.link}
              />
            );
          })}
        </div>
      </Section>
      <Section>
        <SectionHeading>
          Don&apos;t <span className="text-orange-700">Think</span>, Begin{" "}
          <span className="text-orange-700">Today</span>
        </SectionHeading>
      </Section>
    </>
  );
};

export default HomePage;
